### ISSUE TITLE
Please list the package's dependencies using install_requires

### ISSUE THREAD

**Issue by anntzer** [firegurafiku/sphinxcontrib-divparams#1]
setup.py currently documents the dependencies using the requires keyword, which has no effect at all.
Instead, it should use install_requires (https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires).  Moreover, it needs to document beautifulsoup4 as a dependency as well.
Thanks!

**Comment by firegurafiku** [comment]
Oops, I forgot to upload the updated version to PyPI. Now fixed.
